t = templateSVM('SaveSupportVectors',true,'Standardize',true,'Type', ...
                'classification');
[Model1,HyperparameterOptimizationResults] = fitcecoc(K_train, ...
    Trainds.Labels,"Learners",t,"Coding", "onevsall", ...
    'OptimizeHyperparameters',{'BoxConstraint','KernelScale'}, ...
    'HyperparameterOptimizationOptions',struct('KFold',10,'UseParallel', ...
     true));

[predictedLabels_fitcecoc, scores_fitcecoc]= predict(Model1,K_test);
confusionMatrix_fitcecoc = confusionmat(Testds.Labels,predictedLabels_fitcecoc);
fitcecoc_Accuracy = (sum(diag(confusionMatrix))/sum(confusionMatrix(:)))*100